export const products = [
        {
          id: 1,
          title: 'iPhone 9',
          img: 'https://cdn.dummyjson.com/product-images/1/1.jpg',
          brand: 'Apple',
          description: 'An apple mobile which is nothing like apple',
          category: 'smartphones',
          price: 549,
          stock: 94,
          inCart: false,
          count: 1,
        },
        {
        id: 2,
        title: 'iPhone X',
        img: 'https://cdn.dummyjson.com/product-images/2/1.jpg',
        brand: 'Apple',
        description: 'An apple mobile which is nothing like apple',
        category: 'smartphones',
        price: 899,
        stock: 34,
        inCart: false,
        count: 1,
        },
        {
        id: 3,
        title: 'Samsung Universe 9',
        img: 'https://cdn.dummyjson.com/product-images/3/1.jpg',
        brand: 'Samsung',
        description: 'Samsungs new variant which goes beyond Galaxy to the Universe',
        category: 'smartphones',
        price: 1249,
        stock: 36,
        inCart: false,
        count: 1,
        },
        {
        id: 4,
        title: 'OPPOF19',
        img: 'https://cdn.dummyjson.com/product-images/4/1.jpg',
        brand: 'OPPO',
        description: 'OPPO F19 is officially announced on April 2021',
        category: 'smartphones',
        price: 280,
        stock: 123,
        inCart: false,
        count: 1,
        },
        {
        id: 5,
        title: 'Huawei P30',
        img: 'https://cdn.dummyjson.com/product-images/5/1.jpg',
        brand: 'Huawei',
        description: 'Huaweis re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK',
        category: 'smartphones',
        price: 499,
        stock: 32,
        inCart: false,
        count: 1,
        },
        {
        id: 6,
        title: 'MacBook Pro',
        img: 'https://cdn.dummyjson.com/product-images/6/2.jpg',
        brand: 'Apple',
        description: 'MacBook Pro 2021 with mini-LED display may launch between September, November',
        category: 'laptops',
        price: 1749,
        stock: 55,
        inCart: false,
        count: 1,
        },
        {
        id: 7,
        title: 'Samsung Galaxy Book',
        img: 'https://cdn.dummyjson.com/product-images/7/1.jpg',
        brand: 'Samsung',
        description: 'Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched',
        category: 'laptops',
        price: 1499,
        stock: 55,
        inCart: false,
        count: 1,
        },
];

            